---
- hosts: dev
  become: yes
  remote_user: ec2_user
  tasks:
    - name: Install Apache
      yum:
        name: httpd
        state: present
    - name: Install php
      yum:
        name: php
        state: present
    - name: Install php-mysql
      yum:
        name: php-mysql
        state: present
    - name: Download WordPress
      get_url: url=http://wordpress.org/wordpress-latest.tar.gz dest=/var/www/html/wordpress.tar.gz force=yes
    - name: Extract WordPress
      command: "tar xzf /var/www/html/wordpress.tar.gz -C /var/www/html --strip-components 1"   
    - name: Make my directory tree readable
      file:
         path: /var/www/html/
         mode: u=rwX,g=rX,o=rX
         recurse: yes
         owner: apache
         group: apache
    - name: Make sure Apache is started now and at boot.
      service: name=httpd state=started enabled=yes
